[package]
name = "pg-persist"
version = "0.0.1"
edition.workspace = true
license.workspace = true
publish = false

[dependencies]
pg-core = { path = "../../crates/pg-core" }
pg-content = { path = "../../crates/pg-content" }
pg-host = { path = "../../crates/pg-host" }
ruzstd = "0.9.0"
blake3 = { version = "1.8.7", default-features = false, features = ["std", "pure"] }

[dev-dependencies]
proptest = "1.11.0"
