[package]
name = "pg-ai"
version = "0.0.1"
edition.workspace = true
license.workspace = true
publish = false

[dependencies]
pg-core = { path = "../../crates/pg-core" }
pg-content = { path = "../../crates/pg-content" }
pg-host = { path = "../../crates/pg-host" }
serde_json = "1.0.151"

[dev-dependencies]
proptest = "1.11.0"
